seed = [42, 43 ,44] # Shaded area reflects the uncertainty estimated by 3 random seeds

pin_memory = true
num_workers = 1
batch_size = 12
train_size = 0.7
num_epochs = 300
num_splits = 3  # Number of cross-validation splits
num_frames_to_process = 10000
learning_rate = 0.0001
decay = 0.995
patience = 30
device0 = 0
device1 = 1
device2 = 2
device3 = 3
device = 'cpu'

node_dim = 17
vector_dim = 3
edge_dim = 1
cutoff = 1.5
scale = 3
scale_var = 2
num_bins = 20

directory_path = '/home/ziyu/PycharmProjects/pythonProject/small_sys_gnn/small_sys/sys'
data_dir = '/home/ziyu/PycharmProjects/pythonProject/small_sys_gnn/small_sys/sys'




