name: diffusion_egnn
train:
  pin_memory: true
  num_workers: 5
  batch_size: 1
  train_size: 0.7
  num_epochs: 20000
  num_splits: 3  # Number of cross-validation splits
  num_frames_to_process: 10000
  learning_rate: 0.005
  decay: 0.995
  patience: 1000
  #cuda_ids: [0,1,2,3,4,5,6]
  #cuda_ids: [0,1,2,3,4]
  cuda_ids: [5]
  acc_grad_batches: 1
  node_dim: 18
  #edge_type_dim: 4
  cutoff: 2
  scale: 1
  sigma: 0.02 #for flow matching
  #scale_var: 2
  #num_bins: 20
  #directory_path: 'data/sys'
  #data_dir: 'data/sys'
  load_checkpoint: False
  repository_location: /home/florian/Repos/small_molecule
  do_validation: false  # Flag to control validation
  #resume_path: /home/florian/Repos/small_molecule/outputs/2024-07-26/13-31-35/outputs/epoch=429-step=3870.ckpt
  resume_path: /home/florian/Repos/small_molecule/outputs/2024-07-27/12-26-54/outputs/last.ckpt
data:
  pdb_path: "/storage/florian/ziyu_project/ala2/ala2.pdb"
  trajectory_path: "/storage/florian/ziyu_project/ala2/merged_data/trajectory_merged_tensor.pt"
  increments_path: "/storage/florian/ziyu_project/ala2/merged_data/increments_merged_tensor.pt"

